export const PORTRAIT_BUTTONS = [
  {content: 'AC', color: 'gray', width: '25%'},
  {content: '+/-', color: 'gray', width: '49.6%'},
  {
    content: '+',
    color: 'orange',
    width: '25%',
  },
  {content: '1', color: 'gray', width: '25%'},
  {content: '2', color: 'gray', width: '25%'},
  {
    content: '3',
    color: 'gray',
    width: '24.5%',
  },
  {content: '-', color: 'orange', width: '25%'},
  {content: '4', color: 'gray', width: '25%'},
  {content: '5', color: 'gray', width: '25%'},
  {
    content: '6',
    color: 'gray',
    width: '24.5%',
  },
  {content: '*', color: 'orange', width: '25%'},
  {content: '7', color: 'gray', width: '25%'},
  {content: '8', color: 'gray', width: '25%'},
  {
    content: '9',
    color: 'gray',
    width: '24.5%',
  },
  {content: '/', color: 'orange', width: '25%'},
  {content: '0', color: 'gray', width: '25%'},
  {content: '.', color: 'gray', width: '49.6%'},
  {
    content: '=',
    color: 'orange',
    width: '25%',
  },
];

export const LANDSCAPE_BUTTONS = [
  {content: '√x', color: 'gray', width: '16%'},
  {content: 'x!', color: 'gray', width: '16%'},
  {
    content: 'AC',
    color: 'gray',
    width: '17%',
  },
  {content: '+/-', color: 'gray', width: '17%'},
  {content: '%', color: 'gray', width: '17%'},
  {
    content: '+',
    color: 'orange',
    width: '16.5%',
  },
  {content: 'e^x', color: 'gray', width: '16%'},
  {content: '10^x', color: 'gray', width: '16%'},
  {
    content: '1',
    color: 'gray',
    width: '17%',
  },
  {content: '2', color: 'gray', width: '17%'},
  {content: '3', color: 'gray', width: '17%'},
  {
    content: '-',
    color: 'orange',
    width: '16.5%',
  },
  {content: 'ln(x)', color: 'gray', width: '16%'},
  {content: 'log10', color: 'gray', width: '16%'},
  {
    content: '4',
    color: 'gray',
    width: '17%',
  },
  {content: '5', color: 'gray', width: '17%'},
  {content: '6', color: 'gray', width: '17%'},
  {
    content: '*',
    color: 'orange',
    width: '16.5%',
  },
  {content: 'e', color: 'gray', width: '16%'},
  {content: 'x^2', color: 'gray', width: '16%'},
  {
    content: '7',
    color: 'gray',
    width: '17%',
  },
  {content: '8', color: 'gray', width: '17%'},
  {content: '9', color: 'gray', width: '17%'},
  {
    content: '/',
    color: 'orange',
    width: '16.5%',
  },
  {content: 'pi', color: 'gray', width: '16%'},
  {content: 'x^3', color: 'gray', width: '16%'},
  {
    content: '0',
    color: 'gray',
    width: '17%',
  },
  {content: '.', color: 'gray', width: '34.1%'},
  {content: '=', color: 'orange', width: '16.5%'},
];
